'''
-profiles: keys are profile numbers (1-22), values are dictionaries of profile data points
-exceptions: keys are new profile numbers (101-115), values are dictionaries of UWF profile exceptions
    -exceptions are special cases - files with specific combinations of data values that would not normally pass
-vendor_folders: same keys as the profiles dictionary, but the values are arrays of Aspera delivery folders
    -this links specific profiles to the vendors that use them
-provider_strings: a dictionary of provider values with vendor_folder values as keys
    -this links vendor folders to specific providers (e.g., the provider Lionsgate uses the vendor PREMIERE)
'''

profiles = {
    1:{
    'video_codec': 'ProRes',
    'definition': 'HD',
    'frame_height': '1080',
    'frame_width': '1920',
    'frame_rate': 23.98,
    'scan_type': 'progressive',
    'video_bitrate': 150,
    'audio_codec': 'PCM',
    'audio_config': {'layout': '51','bitrate': 0},
    'additional_audio_tracks': {'layout': '20','bitrate': 0},
    },
    2:{
    'video_codec':'ProRes',
    'definition':'HD',
    'frame_height':'1080',
    'frame_width':'1920',
    'frame_rate':23.98,
    'scan_type':'progressive',
    'video_bitrate':50,
    'audio_codec':'PCM',
    'audio_config':{'layout':'51','bitrate':0},
    'additional_audio_tracks':False,
    },
    3:{
    'video_codec':'ProRes',
    'definition':'HD',
    'frame_height':'1080',
    'frame_width':'1920',
    'frame_rate':23.98,
    'scan_type':'progressive',
    'video_bitrate':50,
    'audio_codec':'PCM',
    'audio_config':{'layout':'20','bitrate':0},
    'additional_audio_tracks':False,
    },
    4:{
    'video_codec':'ProRes',
    'definition':'HD',
    'frame_height':'1080',
    'frame_width':'1920',
    'frame_rate':29.97,
    'scan_type':'interlaced',
    'video_bitrate':60,
    'audio_codec':'PCM',
    'audio_config':{'layout':'51','bitrate':0},
    'additional_audio_tracks':False,
    },
    5:{
    'video_codec':'ProRes',
    'definition':'HD',
    'frame_height':'1080',
    'frame_width':'1920',
    'frame_rate':29.97,
    'scan_type':'interlaced',
    'video_bitrate':130,
    'audio_codec':'PCM',
    'audio_config':{'layout':'20','bitrate':0},
    'additional_audio_tracks':False,
    },
    6:{
    'video_codec':'ProRes',
    'definition':'HD',
    'frame_height':'1080',
    'frame_width':'1920',
    'frame_rate':29.97,
    'scan_type':'progressive',
    'video_bitrate':60,
    'audio_codec':'PCM',
    'audio_config':{'layout':'20','bitrate':0},
    'additional_audio_tracks':False,
    },
    7:{
    'video_codec':'ProRes',
    'definition':'SD',
    'frame_height':'480',
    'frame_width':'854',
    'frame_rate':23.98,
    'scan_type':'progressive',
    'video_bitrate':35,
    'audio_codec':'PCM',
    'audio_config':{'layout':'20','bitrate':0},
    'additional_audio_tracks':False,
    },
    8:{
    'video_codec':'ProRes',
    'definition':'SD',
    'frame_height':'480',
    'frame_width':'720',
    'frame_rate':23.98,
    'scan_type':'progressive',
    'video_bitrate':35,
    'audio_codec':'PCM',
    'audio_config':{'layout':'20','bitrate':0},
    'additional_audio_tracks':False
    },
    9:{
    'video_codec':'ProRes',
    'definition':'SD',
    'frame_height':'480',
    'frame_width':'720',
    'frame_rate':29.97,
    'scan_type':'interlaced',
    'video_bitrate':58,
    'audio_codec':'PCM',
    'audio_config':{'layout':'51','bitrate':0},
    'additional_audio_tracks':{'layout':'20','bitrate':0},
    },
    10:{
    'video_codec':'ProRes',
    'definition':'SD',
    'frame_height':'480',
    'frame_width':'720',
    'frame_rate':29.97,
    'scan_type':'interlaced',
    'video_bitrate':60,
    'audio_codec':'PCM',
    'audio_config':{'layout':'20','bitrate':0},
    'additional_audio_tracks':False,
    },
    11:{
    'video_codec':'ProRes',
    'definition':'SD',
    'frame_height':'480',
    'frame_width':'720',
    'frame_rate':29.97,
    'scan_type':'progressive',
    'video_bitrate':55,
    'audio_codec':'PCM',
    'audio_config':{'layout':'20','bitrate':0},
    'additional_audio_tracks':False,
    },
    13:{
    'video_codec':'MP2',
    'definition':'HD',
    'frame_height':'1080',
    'frame_width':'1920',
    'frame_rate':23.98,
    'scan_type':'progressive',
    'video_bitrate':50,
    'audio_codec':'AC3',
    'audio_config':{'layout':'51','bitrate':640},
    'additional_audio_tracks':{'layout':'20','bitrate':192},
    },
    14:{
    'video_codec':'MP2',
    'definition':'HD',
    'frame_height':'1080',
    'frame_width':'1920',
    'frame_rate':23.98,
    'scan_type':'progressive',
    'video_bitrate':45,
    'audio_codec':'PCM',
    'audio_config':{'layout':'51','bitrate':0},
    'additional_audio_tracks':{'layout':'20','bitrate':0},
    },
    15:{
    'video_codec':'MP2',
    'definition':'HD',
    'frame_height':'1080',
    'frame_width':'1920',
    'frame_rate':23.98,
    'scan_type':'progressive',
    'video_bitrate':50,
    'audio_codec':'AC3',
    'audio_config':{'layout':'51','bitrate':640},
    'additional_audio_tracks':False,
    },
    16:{
    'video_codec':'MP2',
    'definition':'HD',
    'frame_height':'1080',
    'frame_width':'1920',
    'frame_rate':23.98,
    'scan_type':'progressive',
    'video_bitrate':50,
    'audio_codec':'PCM',
    'audio_config':{'layout':'51','bitrate':0},
    'additional_audio_tracks':False,
    },
    17:{
    'video_codec':'MP2',
    'definition':'HD',
    'frame_height':'1080',
    'frame_width':'1920',
    'frame_rate':23.98,
    'scan_type':'progressive',
    'video_bitrate':50,
    'audio_codec':'AC3',
    'audio_config':{'layout':'20','bitrate':192},
    'additional_audio_tracks':False,
    },
    18:{
    'video_codec':'MP2',
    'definition':'HD',
    'frame_height':'1080',
    'frame_width':'1920',
    'frame_rate':23.98,
    'scan_type':'progressive',
    'video_bitrate':50,
    'audio_codec':'PCM',
    'audio_config':{'layout':'20','bitrate':0},
    'additional_audio_tracks':False,
    },
    19:{
    'video_codec':'MP2',
    'definition':'SD',
    'frame_height':'480',
    'frame_width':'720',
    'frame_rate':23.98,
    'scan_type':'progressive',
    'video_bitrate':25,
    'audio_codec':'AC3',
    'audio_config':{'layout':'20','bitrate':192},
    'additional_audio_tracks':False,
    },
    20:{
    'video_codec':'MP2',
    'definition':'SD',
    'frame_height':'480',
    'frame_width':'720',
    'frame_rate':29.97,
    'scan_type':'interlaced',
    'video_bitrate':25,
    'audio_codec':'PCM',
    'audio_config':{'layout':'51','bitrate':0},
    'additional_audio_tracks':{'layout':'20','bitrate':0},
    },
    21:{
    'video_codec':'MP2',
    'definition':'SD',
    'frame_height':'480',
    'frame_width':'720',
    'frame_rate':29.97,
    'scan_type':'interlaced',
    'video_bitrate':25,
    'audio_codec':'AC3',
    'audio_config':{'layout':'20','bitrate':192},
    'additional_audio_tracks':False,
    },
    22:{
    'video_codec':'MP2',
    'definition':'SD',
    'frame_height':'480',
    'frame_width':'720',
    'frame_rate':29.97,
    'scan_type':'progressive',
    'video_bitrate':25,
    'audio_codec':'AC3',
    'audio_config':{'layout':'20','bitrate':0},
    'additional_audio_tracks':False,
    }
}

exceptions = {
    101:{
    'video_bitrate':48.3,
    'max_video_bitrate':50,
    'definition':'HD',
    'frame_height':'1080',
    'frame_width':'1920',
    'frame_rate':23.98,
    'scan_type':'progressive',
    'video_codec':'MP2',
    'audio_codec':'AC3',
    'audio_config':{'layout':'51','bitrate':384},
    'additional_audio_tracks':False,
    'exception_fields':['audio_bitrate']
    },
    102:{
    'video_bitrate':75.7,
    'max_video_bitrate':9999,
    'definition':'HD',
    'frame_height':'1080',
    'frame_width':'1920',
    'frame_rate':23.98,
    'scan_type':'progressive',
    'video_codec':'MP2',
    'audio_codec':'AC3',
    'audio_config':{'layout':'51','bitrate':384},
    'additional_audio_tracks':False,
    'exception_fields':['audio_bitrate']
    },
    103:{
    'video_bitrate':50,
    'max_video_bitrate':75.7,
    'definition':'HD',
    'frame_height':'1080',
    'frame_width':'1920',
    'frame_rate':23.98,
    'scan_type':'progressive',
    'video_codec':'MP2',
    'audio_codec':'AC3',
    'audio_config':{'layout':'51','bitrate':384},
    'additional_audio_tracks':False,
    'exception_fields':['audio_bitrate','audio_codec']
    },
    104:{
    'video_bitrate':50,
    'max_video_bitrate':9999,
    'definition':'HD',
    'frame_height':'1080',
    'frame_width':'1920',
    'frame_rate':23.98,
    'scan_type':'progressive',
    'video_codec':'MP2',
    'audio_codec':'AC3',
    'audio_config':{'layout':'51','bitrate':384},
    'additional_audio_tracks':{'layout':'20','bitrate':192},
    'exception_fields':['audio_bitrate','audio_codec','video_bitrate']
    },
    105:{
    'video_bitrate':60,
    'max_video_bitrate':9999,
    'definition':'HD',
    'frame_height':'1080',
    'frame_width':'1920',
    'frame_rate':23.98,
    'scan_type':'progressive',
    'video_codec':'MP2',
    'audio_codec':'MPEG',
    'audio_config':{'layout':'20','bitrate':192},
    'additional_audio_tracks':False,
    'exception_fields':['audio_bitrate','audio_codec']
    },
    106:{
    'video_bitrate':49.1,
    'max_video_bitrate':50,
    'definition':'HD',
    'frame_height':'1080',
    'frame_width':'1920',
    'frame_rate':23.98,
    'scan_type':'progressive',
    'video_codec':'MP2',
    'audio_codec':'MPEG',
    'audio_config':{'layout':'20','bitrate':192},
    'additional_audio_tracks':False,
    'exception_fields':['audio_bitrate','audio_codec']
    },
    107:{
    'video_bitrate':50,
    'max_video_bitrate':60,
    'definition':'HD',
    'frame_height':'1080',
    'frame_width':'1920',
    'frame_rate':23.98,
    'scan_type':'progressive',
    'video_codec':'MP2',
    'audio_codec':'MPEG',
    'audio_config':{'layout':'20','bitrate':192},
    'additional_audio_tracks':False,
    'exception_fields':['audio_bitrate','audio_codec']
    },
    108:{
    'video_bitrate':38.9,
    'max_video_bitrate':49.1,
    'definition':'HD',
    'frame_height':'1080',
    'frame_width':'1920',
    'frame_rate':23.98,
    'scan_type':'progressive',
    'video_codec':'MP2',
    'audio_codec':'MPEG',
    'audio_config':{'layout':'20','bitrate':192},
    'additional_audio_tracks':False,
    'exception_fields':['audio_bitrate','audio_codec']
    },
    109:{
    'video_bitrate':60,
    'max_video_bitrate':9999,
    'definition':'HD',
    'frame_height':'1080',
    'frame_width':'1920',
    'frame_rate':29.97,
    'scan_type':'progressive',
    'video_codec':'MP2',
    'audio_codec':'MPEG',
    'audio_config':{'layout':'20','bitrate':192},
    'additional_audio_tracks':False,
    'exception_fields':['audio_bitrate']
    },
    110:{
    'video_bitrate':60,
    'max_video_bitrate':9999,
    'definition':'HD',
    'frame_height':'1080',
    'frame_width':'1920',
    'frame_rate':23.98,
    'scan_type':'progressive',
    'video_codec':'MP2',
    'audio_codec':'MPEG',
    'audio_config':{'layout':'51','bitrate':640},
    'additional_audio_tracks':False,
    'exception_fields':['audio_bitrate','audio_codec','video_bitrate']
    },
    111:{
    'video_bitrate':50,
    'max_video_bitrate':60,
    'definition':'HD',
    'frame_height':'1080',
    'frame_width':'1920',
    'frame_rate':23.98,
    'scan_type':'progressive',
    'video_codec':'MP2',
    'audio_codec':'MPEG',
    'audio_config':{'layout':'51','bitrate':640},
    'additional_audio_tracks':False,
    'exception_fields':['audio_bitrate','audio_codec']
    },
    112:{
    'video_bitrate':60,
    'max_video_bitrate':9999,
    'definition':'HD',
    'frame_height':'1080',
    'frame_width':'1920',
    'frame_rate':29.97,
    'scan_type':'progressive',
    'video_codec':'MP2',
    'audio_codec':'MPEG',
    'audio_config':{'layout':'51','bitrate':640},
    'additional_audio_tracks':False,
    'exception_fields':['audio_bitrate']
    },
    113:{
    'video_bitrate':15,
    'max_video_bitrate':34,
    'definition':'SD',
    'frame_height':'480',
    'frame_width':'720',
    'frame_rate':23.98,
    'scan_type':'progressive',
    'video_codec':'MP2',
    'audio_codec':'MPEG',
    'audio_config':{'layout':'20','bitrate':192},
    'additional_audio_tracks':False,
    'exception_fields':['audio_bitrate']
    },
    114:{
    'video_bitrate':34,
    'max_video_bitrate':9999,
    'definition':'SD',
    'frame_height':'486',
    'frame_width':'720',
    'frame_rate':23.98,
    'scan_type':'progressive',
    'video_codec':'MP2',
    'audio_codec':'MPEG',
    'audio_config':{'layout':'20','bitrate':192},
    'additional_audio_tracks':False,
    'exception_fields':['framesize']
    },
    115: {
    'video_bitrate': 50.4,
    'max_video_bitrate': 9999,
    'definition': 'SD',
    'frame_height': '486',
    'frame_width': '720',
    'frame_rate': 23.98,
    'scan_type': 'progressive',
    'video_codec': 'ProRes',
    'audio_codec': 'PCM',
    'audio_config':{'layout': '20','bitrate': 0},
    'additional_audio_tracks': False,
    'exception_fields': []
    }
}

vendor_folders = {
    0: [],
    1: ['FOTOKEM','DELUXECA','BITMAX','IMAGE','RLJ','INCEPTIONMG'],
    2: ['INCEPTIONMG','VISUALDATA','DUPSERVICE','PREMIERE','2GDIGITAL','STARZ'],
    3: ['FOTOKEM','BBCW','MVF','MVD','INCEPTIONMG','FILMSALES','BITMAX','VISUALDATA','DUPSERVICE','PREMIERE','DELUXECA','NBCUNI','UNIPROMOTION','DELUXE','NBCUNI2','ORCHARD','IMAGE','RLK','2GDIGITAL','STARZ','TRIBECA'],
    4: ['NBCUNI','UNIPROMOTION','DELUXE','DELUXECA','NBCUNI2'],
    5: ['BBCW','NBCUNI','UNIPROMOTION','DELUXECA','DELUXE','NBCUNI2','IMAGE','RLJ','INCEPTIONMG','UFCVOD'],
    6: ['MVF','MVD','INCEPTIONMG','FILMSALES','BITMAX'],
    7: ['DPS','VERTICAL'],
    8: ['MVF','MVD','INCEPTIONMG','FILMSALES','BITMAX','DELUXECA','IMAGE','RLJ'],
    9: ['FOTOKEM'],
    10: ['BBCW','DELUXECA','IMAGE','RLJ','INCEPTIONMG'],
    11: ['MVF','MVD','INCEPTIONMG','FILMSALES','BITMAX','PREMIERE'],
    13: ['TECHNICOLORCA','INCEPTIONMG','DELUXETORONTO'],
    14: ['PARAMOUNT2'],
    15: ['INCEPTIONMG','NBCUNI','UNIPROMOTION','DELUXE','DELUXECA','NBCUNI2'],
    16: ['PARAMOUNT2'],
    17: ['INCEPTIONMG','TECHNICOLORCA','INCEPTIONMG','DELUXETORONTO','NBCUNI','UNIPROMOTION','DELUXE','DELUXECA','NBCUNI2','IMAGE','RLJ','DETE_PUSH','GDMX'],
    18: ['PARAMOUNT2'],
    19: ['INCEPTIONMG','IMAGE','RLJ','DELUXECA'],
    20: ['PARAMOUNT2','DPS','VERTICAL'],
    21: ['PARAMOUNT2','DETE_PUSH','GDMX'],
    22: ['MVF','MVD','INCEPTIONMG','FILMSALES','BITMAX'],
    101: ['DELUXECA'],
    102: ['IMAGE','RLJ','DELUXECA','INCEPTIONMG'],
    103: ['DETE_PUSH','GDMX'],
    104: ['PARAMOUNT2'],
    105: ['FOX','PREMIERE','DETE_PUSH','GDMX'],
    106: ['FOX'],
    107: ['PREMIERE','DETE_PUSH','GDMX'],
    108: ['PBS2','PBSINDIES','IMAGE'],
    109: ['NBCUNI','UNIPROMOTION','DELUXE','DELUXECA','NBCUNI2'],
    110: ['FOX','PREMIERE','DETE_PUSH','GDMX'],
    111: ['PREMIERE','DETE_PUSH','GDMX'],
    112: ['NBCUNI','UNIPROMOTION','DELUXE','DELUXECA','NBCUNI2'],
    113: ['FOX'],
    114: ['PBS2','PBSINDIES','IMAGE','FOX'],
    115: ['ORCHARD']
}

provider_strings = {
    'FOTOKEM':'Alchemy_Millenium',
    'INCEPTIONMG':'A24_eOne_Phase4_Gravitas_IFC_Lantern_Lane_The_Asylum_RLJ_Image',
    'BBCW':'BBCA_EST',
    'TECHNICOLORCA':'eOne_Phase4',
    'DELUXETORONTO':'eOne_Phase4',
    'FOX':'Fox',
    'MVF':'Gravitas',
    'MVD':'Gravitas',
    'FILMSALES':'Gravitas',
    'BITMAX':'Gravitas_MarVista',
    'VISUALDATA':'Lantern_Lane_The_Asylum',
    'DUPSERVICE':'Lantern_Lane_The_Asylum',
    'PREMIERE':'Lionsgate',
    'DELUXECA':'MGM_NBCU_RELATIVITY_RLJ_Image',
    'NBCUNI':'NBCU',
    'UNIPROMOTION':'NBCU',
    'NBCUNI2':'NBCU',
    'DELUXE':'NBCU',
    'IMAGE':'PBS_RLJ_Image',
    'RLJ':'RLJ_Image',
    'PARAMOUNT2':'Paramount',
    'PBS2':'PBS',
    'PBSINDIES':'PBS',
    '2GDIGITAL':'Sony',
    'STARZ':'STARZ_EST',
    'ORCHARD':'The_Orchard',
    'TRIBECA':'Tribeca',
    'UFCVOD':'UFC',
    'DPS':'Vertical',
    'VERTICAL':'Vertical',
    'DETE_PUSH':'WB',
    'GDMX':'WB',
    'Unknown':'Unknown'
}
